### ISSUE TITLE
(bug) Button ok

### ISSUE THREAD

**Issue by 3xploiton3** [joshuawolfsohn/Private-DNS-Quick-Tile#1]
![](https://i.imgur.com/ii9h8Nd.jpg)

Bug button OK not showing

**Comment by joshuawolfsohn** [comment]
What device are you using?

**Comment by 3xploiton3** [comment]
Redmi note 5 ai,  rom from xiaomi.eu 9.10.10

**Comment by joshuawolfsohn** [comment]
Hi 3xploiton3, I haven't had time to work on this issue yet, but I'll be working on an updated version with a fix sometime this month. Thanks for your patience.

**Comment by joshuawolfsohn** [comment]
Fixed in latest v1.5

**Comment by 3xploiton3** [comment]
please, push update to f-droid

> Fixed in latest v1.5

**Comment by joshuawolfsohn** [comment]
> please, push update to f-droid
> 
> > Fixed in latest v1.5

Refresh your F-Droid repos, 1.5 was pushed last week
