### ISSUE TITLE
How To Use ?

### ISSUE THREAD

**Issue by varunsridharan** [joshuawolfsohn/Private-DNS-Quick-Tile#2]
Hi There

I would like to know how i can install this app in Android OS ?

**Comment by joshuawolfsohn** [comment]
Thanks for inquiring Varun. I'll be updating this app's Github page sometime this month with a proper README and a link to the latest installable .apk package. In the meantime, you can download the app from F-Droid: https://f-droid.org/en/packages/com.jpwolfso.privdnsqt/

**Comment by varunsridharan** [comment]
If you want i can publish this app in Google Play Store.

**Comment by joshuawolfsohn** [comment]
No thanks, but feel free to either download and build the app in Android Studio yourself or download an installable .apk of the app from F-Droid :)
