### ISSUE TITLE
Configuration of quick settings toggle doesn't save

### ISSUE THREAD

**Issue by AnonRS3** [joshuawolfsohn/Private-DNS-Quick-Tile#3]
If you long press the quick settings icon and make changes to the configuration (such as disabling the "auto" option), the settings are not saved when you go to toggle the quick settings icon later on.  So even if I choose to disable the "auto" option, the quick settings tile still allows me to toggle it, showing the option to disable it isn't working.

**Comment by joshuawolfsohn** [comment]
Thanks for bringing this up Marissa! When you're making changes to the configuration, are you pressing the "OK" button to save your changes? Let me know, and I'll look at my code too. I haven't had time to touch coding since last fall, so I'll be updating the app sometime soon this month.

**Comment by AnonRS3** [comment]
I just checked, and it looks like when I open the settings menu, the OK button isn't showing up for me, so I am unable to save my changed settings. 

![](https://i.imgur.com/HUg02z4.png)

**Comment by AnonRS3** [comment]
By accident, I found the OK button, but it looks like the text on it is extremely small: 

![](https://i.imgur.com/KK1X6ev.png) 

For reference, here is my device information:

Google Pixel 3
Android 10

**Comment by joshuawolfsohn** [comment]
Hi Marissa, thanks again for the feedback. An update to the app should be available on F-Droid in a few days, but you can build the latest release from source if you'd like. The update will change the "Private DNS Quick Tile Modes" screen to a fullscreen activity that now uses a ConstraintLayout, so everything should render at an appropriate size on all devices now. Let me know if the problem has been resolved here once you get a chance to test out the new release.

**Comment by AnonRS3** [comment]
Awesome, once I get the update I'll check to see if it works!

**Comment by joshuawolfsohn** [comment]
Thanks for your patience, the new version is now available on F-Droid! Let me know if the issue is still present for you, or if it has been resolved :)

**Comment by AnonRS3** [comment]
I just received the update on F-Droid. The save button is now displaying properly. Thank you!
